name: Run Postman collection

on: 
  workflow_dispatch:

jobs:
  postman-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run ./test-weather-api.json \
            --env-var apiKey=$API_KEY \
            --reporters cli,html \
            --reporter-html-export newman/newman-report.html
        env:
          API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

      - name: List files for debugging
        run: ls -la

      - name: Upload Newman Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: ./newman-report.html
